### ISSUE TITLE
Support `protoreflect.Map` field type

### ISSUE THREAD

**Issue by thepabloaguilar** [faunists/deal-go#5]
We need to support the `protoreflect.Map` in our [processor field](https://github.com/faunists/deal-go/blob/main/processors/fields.go#L17) function that formats the message to its string representation!

- [ ] Make the function works correctly with`protoreflect.Map`
- [ ] Write tests to stress as many possibilities as possible

**Comment by krishnaindani** [comment]
hey, I would like to attempt on this? Could you be able to guide me? I am contributing first time to this project

**Comment by thepabloaguilar** [comment]
Hey @krishnaindani sorry for the late, you're more than welcome!

I can try to guide you in this issue, what we need is once the user has defined a proto with a map and provided its value in the json:
```proto
message SomeMessage {
    map<string, string> some_attr = 1;
}
```

```json
  ...
  "some_attr": {"some_value": "some_value"}
  ...
```

We need to transform them in a valid Golang format:
```go
&SomeMessage{SomeAttr: map[string]string{"some_value": "some_value"}
```

In order to do that you must need to know how to:
- Get the key type
- Get the value type
- Get all the map values and transform them (here you can call `FormatFieldValue` recursively)

**Comment by thepabloaguilar** [comment]
Important thing, a key from a map can be just:
* bool
* int32
* int64
* uint32
* uint64
* string
