### ISSUE TITLE
Support `protoreflect.EnumNumber` field type

### ISSUE THREAD

**Issue by thepabloaguilar** [faunists/deal-go#6]
We need to support the `protoreflect.EnumNumber` in our [processor field](https://github.com/faunists/deal-go/blob/main/processors/fields.go#L17) function that formats the message to its string representation!

- [ ] Make the function works correctly with`protoreflect.EnumNumber`
- [ ] Write tests to stress as many possibilities as possible

**Comment by florkbr** [comment]
PR open! #hacktoberfest 🍺

**Comment by thepabloaguilar** [comment]
Hey @florkbr, I'll review it ASAP
